version: 2.1
orbs:
  lambroll: fujiwara/lambroll@0.0.8
jobs:
  deloy:
    docker:
      - image: cimg/base
    steps:
      - checkout
      - lambroll/install:
          version: v0.10.0
      - run:
          command: |
            lambroll deploy