version: 2.1
orbs:
  lambroll: fujiwara/lambroll@0.0.8
jobs:
  deploy:
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      - lambroll/install:
          version: v0.10.0
      - run:
          command: |
            apt install python-pip python3-pip
            pip install -r requirements.txt -t .
            zip -r function.zip *
            lambroll deploy --region="ap-northeast-1" --function="function.json" --src="function.zip"
workflows:
  deploy:
    jobs:
      - deploy